### PR TITLE
Fix doodle

### PR DESCRIPTION
**Pull request by mikeyrayvon**
keyframe.isSupported is broken in Chrome 58. had to take that out.

### CODE REVIEW

**Review by varffs — COMMENTED** [review]
Looks fine. But what is the solution here where the isSupported function used to prevent the styles being added when not supported? If they are added unsupported does it break anything?

**Comment by mikeyrayvon** [comment]
hm its weird cause. when i `console.log($.keyframe.isSupported())` in the program, it returns `false`. but when i run `$.keyframe.isSupported()` in the console, it returns `true`

**Comment by mikeyrayvon** [comment]
any idea why that is?

**Comment by mikeyrayvon** [comment]
documentation for jQuery.Keyframes says that function detects support for CSS animations, which is already very well supported: http://caniuse.com/#search=animation. and jQuery.Keyframes adds the `-webkit-` prefix so Safari 6,7,8 would still be ok. jQuery.Keyframes development started back in 2012 when CSS animations had little support. So I suppose thats the reason for this detection function.

**Pull request merged**
